services:
  tradingview-snapshot:
    build: .
    restart: always
    ports:
      - 3000
    volumes:
      - ./screenshots:/app/screenshots
    environment:
      - NODE_ENV=production
    networks:
      - dokploy-network
    labels:
      - traefik.http.routers.tradingview-snapshot-web.rule=Host(`tview.dp.tamer.im`)
      - traefik.http.routers.tradingview-snapshot-web.entrypoints=web
      - traefik.http.services.tradingview-snapshot-web.loadbalancer.server.port=3000
      - traefik.http.routers.tradingview-snapshot-web.service=tradingview-snapshot-web
      - traefik.http.routers.tradingview-snapshot-web.middlewares=redirect-to-https@file
      - traefik.http.routers.tradingview-snapshot-websecure.rule=Host(`tview.dp.tamer.im`)
      - traefik.http.routers.tradingview-snapshot-websecure.entrypoints=websecure
      - traefik.http.services.tradingview-snapshot-websecure.loadbalancer.server.port=3000
      - traefik.http.routers.tradingview-snapshot-websecure.service=tradingview-snapshot-websecure
      - traefik.http.routers.tradingview-snapshot-websecure.tls.certresolver=letsencrypt
      - traefik.http.routers.tradingview-snapshot-websecure.tls=true
      - traefik.enable=true

networks:
  dokploy-network:
    external: true

volumes:
  screenshots: