services:
  tradingview-snapshot:
    build: .
    restart: always
    ports:
      - 3000
    volumes:
      - ./screenshots:/app/screenshots
    environment:
      - NODE_ENV=production
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tradingview-snapshot.rule=Host(`tview.dp.tamer.im`)"
      - "traefik.http.routers.tradingview-snapshot.entrypoints=websecure"
      - "traefik.http.routers.tradingview-snapshot.tls.certResolver=letsencrypt"
      - "traefik.http.services.tradingview-snapshot.loadbalancer.server.port=3000"

networks:
  dokploy-network:
    external: true

volumes:
  screenshots: